# version: '3.8'
# services:
#   app:
#     image: servicerouter
#     ports:
#       - "3090:3090"
#     environment:
#       - DB_HOST=103.151.33.111
#       - DB_PORT=3306
#       - DB_USER=root
#       - DB_PASSWORD=hesoyam404@
#     networks:
#       - x86_default
#     command: [ "node", "index.js" ]

# networks:
#   x86_default:
#     external: true
#     driver: bridge


# version: '3.8'
# services:
#   app:
#     build:
#       context: .
#     ports:
#       - "3090:3090"
#     environment:
#       - DB_HOST=103.151.33.111
#       - DB_PORT=3306
#       - DB_USER=root
#       - DB_PASSWORD=hesoyam404@
#     networks:
#       - x86_default
#     command: [ "node", "index.js" ]

# networks:
#   x86_default:
#     external: true
#     driver: bridge


version: '3.8'

services:
  route-service:
    build: .
    ports:
      - "3090:3090"
    environment:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD: hesoyam404
      DB_NAME: maxnet_billing
