services:
  app:
    image: servicerouter
    ports:
      - "3090:3090"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=hesoyam404
    networks:
      - servicerouter

  db:
    image: mysql:8.0.37
    environment:
      - MYSQL_ROOT_PASSWORD=hesoyam404
    ports:
      - "3307:3306"
    networks:
      - servicerouter

networks:
  servicerouter:
    external: true